### PR TITLE
fix: fail gracefully when unable to fetch an image

### PR DESCRIPTION
**Pull request by lmaos-code**
Hi. I had an issue with a link, where no image was found by the crestify service. (It was this [Twitter Link](https://twitter.com/_alexbrogan/status/1576199043537149952) [don't know what's wrong with it])
I fixed it, so that no image will be rendered, if there is none to render.

Not only that, but I also found it odd, that there was no feedback to the User, if something went wrong whilst creating the rich link. Therefore, I added a blanket statement that something went wrong

### CODE REVIEW

**Comment by lmaos-code** [comment]
Also, just being curious. Is there a reason, you don't have a `package-lock.json` (or even better, a `pnpm-lock.json`) in your repo?

**Comment by dhamaniasad** [comment]
Can you share an image of how the card looks? I'll review and merge the MR soon.

**Comment by lmaos-code** [comment]
Sorry for the late reply.
A card, without an image, would look like this:
Example Image

**Comment by dhamaniasad** [comment]
Missed your message before. If you reopen the MR I'll merge it.

**Pull request closed without merging**
